name: Release

on:
  push:
    tags:
      - 'visui-*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Make Gradle executable
        run: chmod +x gradlew
      - name: Run tests
        run: ./gradlew check
      - name: Upload to Maven Central
        run: ./gradlew uploadArchives
        env:
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.ossrhUsername }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.ossrhPassword }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.signingKeyId }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.signingPassword }}
      - name: Close Maven repository
        run: ./gradlew closeRepository
        env:
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.ossrhUsername }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.ossrhPassword }}
#      - name: Release Maven repository
#        run: ./gradlew releaseRepository
#        env:
#          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.ossrhUsername }}
#          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.ossrhPassword }}
